services:
  - type: web
    name: chashma-bot
    runtime: python
    repo: https://github.com/bahodirjamolov119-afk/chashma-bot.git
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
